### PR TITLE
Fix donate command

### LINKED ISSUE #131: Update Donate Command Test and Donate Command Parser Test

### PR DESCRIPTION
**Pull request by jinhanfromNUS**
closes #131

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/DonateCommandTest.java [hunk 1]
```diff
@@ -30,12 +30,12 @@ public void execute_returnUnfilteredList_success() {
 
         DonateCommand donateCommand = new DonateCommand(INDEX_KEPLER, new Book(bookTitle));
 
-        String expectedMessage = String.format(DonateCommand.MESSAGE_DONATE_SUCCESS, editedPerson);
+        String expectedMessage = String.format(DonateCommand.MESSAGE_DONATE_SUCCESS, editedPerson, new Book(bookTitle));
 
         Model expectedModel = new ModelManager(new AddressBook(model.getAddressBook()), new UserPrefs(),
                 new Library(model.getLibrary()));
         expectedModel.setPerson(KEPLER, editedPerson);
-
```
Comment (Darkarche3) [inline src/test/java/seedu/address/logic/commands/DonateCommandTest.java:38]: Trailing whitesspace

**Review by Darkarche3 — APPROVED** [review]

File: src/test/java/seedu/address/logic/commands/DonateCommandTest.java (hunk 1 above)
Comment (jinhanfromNUS) [reply src/test/java/seedu/address/logic/commands/DonateCommandTest.java:38]: Done thanks
